import { useEffect, useMemo, useState } from 'react';
import { ShieldCheck, LogOut, User, FolderKanban, Wrench, GraduationCap, Award, Image, FileText, Settings, Link as LinkIcon, Plus, Trash2, Pencil, RefreshCw } from 'lucide-react';
import { portfolioApi } from './api';
import './styles.css';

const labels = [['Overview',ShieldCheck],['Profile',User],['Projects',FolderKanban],['Skills',Wrench],['Education',GraduationCap],['Experience',GraduationCap],['Achievements',Award],['Certificates',Award],['Media',Image],['CV',FileText],['Social Links',LinkIcon],['Settings',Settings]];
const kinds = {Projects:'project',Skills:'skill',Education:'education',Experience:'experience',Achievements:'achievement',Certificates:'certificate',Media:'media',CV:'cv','Social Links':'social',Profile:'profile'};

function Editor({kind, initial, onSaved, onCancel}) {
 const [title,setTitle]=useState(initial?.title||''); const [description,setDescription]=useState(initial?.data?.description||''); const [url,setUrl]=useState(initial?.data?.url||''); const [published,setPublished]=useState(initial?.published ?? true); const [saving,setSaving]=useState(false); const type=kinds[kind];
 async function save(e){e.preventDefault();setSaving(true);try{const body={kind:type,title,data:{description,url},published}; if(initial) await portfolioApi.update(initial._id,body); else await portfolioApi.create(body);onSaved()}catch(e){alert(e.message)}finally{setSaving(false)}}
 return <form className="editor" onSubmit={save}><h3>{initial?'Edit':'Add'} {kind}</h3><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} required /></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} /></label><label>URL<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..." /></label><label className="check"><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/> Published</label><div className="editor-actions"><button type="button" onClick={onCancel}>Cancel</button><button className="save" disabled={saving}>{saving?'Saving…':'Save'}</button></div></form>
}

export default function App(){
 const [user,setUser]=useState(null),[loading,setLoading]=useState(true),[active,setActive]=useState('Overview'),[data,setData]=useState([]),[busy,setBusy]=useState(false),[editing,setEditing]=useState(null);
 const load=()=>{setBusy(true);portfolioApi.list().then(setData).catch(e=>{if(e.message.includes('401'))setUser(null);else alert(e.message)}).finally(()=>setBusy(false))};
 useEffect(()=>{fetch(`${import.meta.env.VITE_API_URL||'http://localhost:5000'}/api/auth/me`,{credentials:'include'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setUser(d.user)).catch(()=>setUser(null)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(user)load()},[user]);
 const rows=useMemo(()=>data.filter(x=>x.kind===kinds[active]),[data,active]);
 if(loading)return <div className="admin-loading">Checking secure session…</div>;
 if(!user)return <main className="login"><div className="login-card"><div className="shield"><ShieldCheck/></div><p className="eyebrow">ARCANGE ADMIN</p><h1>Private workspace.</h1><p>Sign in with your authorized Google account to manage your portfolio.</p><a className="google-btn" href={`${import.meta.env.VITE_API_URL||'http://localhost:5000'}/api/auth/google`}><span>G</span> Continue with Google</a><a className="back" href="/">← Back to portfolio</a></div></main>;
 async function remove(id){if(!confirm('Delete this item?'))return;try{await portfolioApi.remove(id);load()}catch(e){alert(e.message)}}
 return <div className="dashboard"><aside><div className="brand">ARCANGE<span>.</span></div><p className="admin-label">ADMIN PANEL</p><nav>{labels.map(([name,Icon])=><button className={active===name?'active':''} onClick={()=>{setActive(name);setEditing(null)}} key={name}><Icon size={17}/>{name}</button>)}</nav><div className="side-user"><img src={user.photo||''} alt=""/><div><strong>{user.name}</strong><small>{user.email}</small></div></div></aside><section className="main"><header><div><p className="eyebrow">SECURE CMS</p><h2>{active}</h2></div><button className="logout" onClick={async()=>{await fetch(`${import.meta.env.VITE_API_URL||'http://localhost:5000'}/api/auth/logout`,{method:'POST',credentials:'include'});location.reload()}}><LogOut size={16}/> Logout</button></header><div className="content">{active==='Overview'?<><div className="welcome"><div><p className="eyebrow">WELCOME BACK</p><h1>Control your digital identity.</h1><p>Authenticated as <strong>{user.email}</strong>. Manage your portfolio content from this protected workspace.</p></div><ShieldCheck size={80}/></div><div className="stats"><div><span>{data.length}</span><strong>Total content</strong><p>Published and draft CMS items</p></div><div><span>{data.filter(x=>x.published).length}</span><strong>Published</strong><p>Visible on the public site</p></div><div><span>{new Set(data.map(x=>x.kind)).size}</span><strong>Content types</strong><p>Managed from this dashboard</p></div></div></>:active==='Settings'?<div className="empty"><Settings size={34}/><h3>Site settings</h3><p>Copyright, branding and global configuration will be connected to the settings collection in the next CMS pass.</p></div>:<div className="module"><div className="module-head"><div><p className="eyebrow">CONTENT MANAGER</p><h3>{active}</h3></div><div><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={16}/></button><button className="add" onClick={()=>setEditing('new')}><Plus size={16}/> Add</button></div></div>{editing?<Editor kind={active} initial={editing==='new'?null:editing} onSaved={()=>{setEditing(null);load()}} onCancel={()=>setEditing(null)}/>:busy?<p>Loading…</p>:rows.length===0?<div className="empty small"><h3>No {active.toLowerCase()} yet</h3><p>Use Add to create your first entry.</p></div>:<div className="table">{rows.map(row=><div className="row" key={row._id}><div><strong>{row.title}</strong><small>{row.data?.description||'No description'}</small></div><span className={row.published?'status on':'status'}>{row.published?'Published':'Draft'}</span><div className="row-actions"><button onClick={()=>setEditing(row)}><Pencil size={15}/></button><button onClick={()=>remove(row._id)}><Trash2 size={15}/></button></div></div>)}</div>}</div>}</div></section></div>
}
