import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowDown, ArrowUpRight, Award, Bot, Check, Code2, Database, ExternalLink, FileText, GraduationCap, Mail, MapPin, Menu, MessageCircle, Monitor, Sparkles, X } from 'lucide-react';
import './styles.css';

const fallbackSkills=['Python','C','C++','Java','JavaScript','HTML5','CSS3','React.js','Node.js','Express.js','Electron.js','MongoDB','MySQL','SQL','NoSQL'];
const fallbackProjects=[
 {title:'Munyarwanda AI',category:'AI / RAG',description:'A Kinyarwanda-focused AI project exploring retrieval-augmented generation and AI integration.'},
 {title:'Arcange AI Assistant',category:'AI / Desktop',description:'A personal AI assistant concept combining desktop software with AI APIs.'},
 {title:'NextBit Updates',category:'Technology Media',description:'A technology and ICT news brand focused on digital developments.'},
 {title:'NextByte Academy',category:'Education',description:'A technology learning platform concept for practical programming education.'}
];
const fallbackSocials=[['GitHub','https://github.com/arcange9'],['Instagram','https://instagram.com/arcangegram'],['Telegram','https://t.me/izerearcange'],['Facebook','https://facebook.com/arcange.froky']];
const projectIcons=[Bot,Monitor,Sparkles,GraduationCap];

function Section({eyebrow,title,children,id,accent}){return <section id={id} className="section"><div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{accent&&<span className="section-line"/>}</div>{children}</section>}

export default function App(){
 const [content,setContent]=useState(null),[menuOpen,setMenuOpen]=useState(false),[progress,setProgress]=useState(0),[copied,setCopied]=useState(false);
 useEffect(()=>{const api=import.meta.env.VITE_API_URL;if(!api)return;fetch(`${api}/api/content/public`,{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(setContent).catch(()=>{});},[]);
 useEffect(()=>{const onScroll=()=>{const max=document.documentElement.scrollHeight-window.innerHeight;setProgress(max>0?(window.scrollY/max)*100:0)};window.addEventListener('scroll',onScroll,{passive:true});onScroll();return()=>window.removeEventListener('scroll',onScroll)},[]);
 const profile=content?.profile||{};
 const skills=content?.skills?.map(x=>x.name).filter(Boolean)?.length?content.skills.map(x=>x.name).filter(Boolean):fallbackSkills;
 const projects=content?.projects?.length?content.projects:fallbackProjects;
 const experience=content?.experience||[];
 const education=content?.education||[];
 const achievements=content?.achievements||[];
 const certificates=content?.certificates||[];
 const settings=content?.settings||{};
 const socials=content?.socials?.length?content.socials.map(x=>[x.label||x.platform,x.url]):fallbackSocials;
 const year=settings.autoUpdateCopyrightYear===false?settings.copyrightStartYear||new Date().getFullYear():new Date().getFullYear();
 const colors={primary:'#8b5cf6',secondary:'#ff4ecd',accent:'#42e8ff',background:'#070711',surface:'#111120',text:'#f7f7fb',muted:'#aaaabd',...(settings.colors||{})};
 const theme=useMemo(()=>({'--primary':colors.primary,'--secondary':colors.secondary,'--accent':colors.accent,'--bg':colors.background,'--surface':colors.surface,'--text':colors.text,'--muted':colors.muted}),[colors.primary,colors.secondary,colors.accent,colors.background,colors.surface,colors.text,colors.muted]);
 const stats=[['Projects',projects.length,'selected builds'],['Technologies',skills.length,'tools in the stack'],['Learning',education.length+certificates.length,'education & credentials'],['Experience',experience.length,'training & roles']];
 const email=profile.email||'';
 async function copyEmail(){if(!email)return;try{await navigator.clipboard.writeText(email);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{window.location.href=`mailto:${email}`}}
 const scrollTo=(id)=>{setMenuOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};
 return <div className="site" style={theme}>
  <div className="scroll-progress"><span style={{width:`${progress}%`}}/></div>
  <nav className="nav"><a className="logo" href="#home" onClick={()=>setMenuOpen(false)}>ARCANGE<span>.</span></a><button className="menu-toggle" onClick={()=>setMenuOpen(v=>!v)} aria-label="Toggle navigation">{menuOpen?<X/>:<Menu/>}</button><div className={`links ${menuOpen?'open':''}`}>{['about','skills','projects','education','experience','contact'].map(id=><a key={id} href={`#${id}`} onClick={()=>setMenuOpen(false)}>{id[0].toUpperCase()+id.slice(1)}</a>)}</div></nav>
  <main>
   <section id="home" className="hero"><div className="hero-grid"/><div className="orb orb1"/><div className="orb orb2"/><div className="hero-topline"><motion.p initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="eyebrow">SOFTWARE • AI • COMPUTER SYSTEMS</motion.p><span className="availability"><i/> Open to learning & building</span></div>
    <div className="hero-identity">{profile.photoUrl?<motion.img initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} src={profile.photoUrl} alt={profile.name||'Profile'}/>:<div className="avatar-placeholder"><Sparkles size={28}/></div>}<div><motion.p initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="mini-label">WELCOME TO MY DIGITAL SPACE</motion.p><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.08}}>{profile.name||'Mukamyi Izere Arcange'}</motion.h1><p className="lead">{profile.title||'Software developer, AI builder and Computer Systems & Architecture student creating practical digital experiences.'}</p></div></div>
    <div className="actions"><a className="button primary" href="#projects">Explore my work <ArrowUpRight size={17}/></a>{profile.resumeUrl&&<a className="button" href={profile.resumeUrl} target="_blank" rel="noreferrer"><FileText size={16}/> View CV</a>}<button className="button" onClick={()=>scrollTo('contact')}><Mail size={16}/> Contact me</button></div>
    <div className="hero-meta"><div className="hero-location"><MapPin size={15}/><span>{profile.location||'Rwanda'}</span></div><div className="hero-stat"><strong>{projects.length}+</strong><span>projects / ideas</span></div><div className="hero-stat"><strong>{skills.length}</strong><span>technologies</span></div></div>
    <div className="hero-tags">{skills.slice(0,8).map(s=><span key={s}>{s}</span>)}</div><a className="scroll-cue" href="#about"><span>Scroll to explore</span><ArrowDown size={15}/></a>
   </section>
   <div className="stats-strip">{stats.map(([label,value,sub])=><div className="stat-card" key={label}><span className="stat-number">{value}</span><strong>{label}</strong><small>{sub}</small></div>)}</div>
   <Section id="about" eyebrow="01 / ABOUT" title="Building with curiosity, code & technology." accent><div className="about-layout"><div><p className="text">{profile.longBio||'I am focused on programming, web development, AI, databases and computer systems. This portfolio brings together the projects, technical interests, learning journey and experiments I build as I grow as a developer.'}</p><div className="about-pills"><span><Check size={15}/> Practical</span><span><Check size={15}/> Curious</span><span><Check size={15}/> Always learning</span></div></div><div className="feature-row"><div><Code2/><strong>Software</strong><span>Web & desktop applications</span></div><div><Bot/><strong>AI</strong><span>AI integration & RAG</span></div><div><Database/><strong>Data</strong><span>SQL & NoSQL databases</span></div></div></div></Section>
   <Section id="skills" eyebrow="02 / TECHNOLOGIES" title="A growing technical toolbox." accent><div className="skill-grid">{skills.map((s,i)=><motion.div whileHover={{y:-6,scale:1.02}} className="skill" key={s}><small>{String(i+1).padStart(2,'0')}</small><strong>{s}</strong><span>{i<4?'CORE':i<9?'DEVELOPMENT':'TOOLKIT'}</span></motion.div>)}</div></Section>
   <Section id="projects" eyebrow="03 / SELECTED WORK" title="Projects with purpose." accent><div className="project-grid">{projects.map((p,i)=>{const Icon=projectIcons[i%projectIcons.length];return <motion.article whileHover={{y:-8}} className={`card ${p.featured?'featured-card':''}`} key={p._id||p.title||p.name}>{p.imageUrl&&<img className="card-image" src={p.imageUrl} alt={p.title||p.name}/>}<div className="card-top"><span>0{String(i+1).padStart(1,'0')}</span>{p.featured&&<em>FEATURED</em>}<Icon className="card-icon"/></div><p>{p.category||p.data?.category||'PROJECT'}</p><h3>{p.title||p.name}</h3><div className="card-description">{p.description||p.data?.description||''}</div>{Array.isArray(p.technologies)&&p.technologies.length>0&&<div className="tech-list">{p.technologies.slice(0,4).map(t=><span key={t}>{t}</span>)}</div>}<div className="card-actions">{p.githubUrl&&<a href={p.githubUrl} target="_blank" rel="noreferrer"><Code2 size={15}/> GitHub</a>}{p.liveUrl&&<a href={p.liveUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/> Live</a>}{!p.githubUrl&&!p.liveUrl&&p.data?.url&&<a href={p.data.url} target="_blank" rel="noreferrer"><ExternalLink size={15}/> View project</a>}</div></motion.article>})}</div></Section>
   {education.length>0&&<Section id="education" eyebrow="04 / EDUCATION" title="Learning and growing." accent><div className="timeline-grid">{education.map(item=><article className="info-card" key={item._id}><GraduationCap/><h3>{item.program}</h3><p className="meta">{item.institution}{item.level?` · ${item.level}`:''}</p><p>{item.startYear||''}{item.endYear?` — ${item.endYear}`:''}</p><p>{item.description}</p></article>)}</div></Section>}
   <Section id="experience" eyebrow="05 / TRAINING & EXPERIENCE" title="Learning through real programs." accent><div className="experience-list">{(experience.length?experience:[{organization:'Ejo Labs — Technology Training Program',role:'Technology Training',type:'Training',description:'Participated in a one-month technology training program, developing practical knowledge around AI integration, Retrieval-Augmented Generation (RAG), software development and collaborative project work.'}]).map((item,i)=><article className="experience" key={item._id||item.organization}><div className="experience-index">0{i+1}</div><div className="experience-badge"><GraduationCap/></div><div className="experience-content"><div className="experience-head"><div><h3>{item.organization}</h3><p className="meta">{item.role||item.type}</p></div>{item.startDate&&<span className="date-chip">{new Date(item.startDate).getFullYear()}</span>}</div><p>{item.description}</p>{Array.isArray(item.technologies)&&item.technologies.length>0&&<div className="tech-list">{item.technologies.map(t=><span key={t}>{t}</span>)}</div>}</div></article>)}</div></Section>
   {achievements.length>0&&<Section id="achievements" eyebrow="06 / ACHIEVEMENTS" title="Milestones worth remembering." accent><div className="timeline-grid">{achievements.map(item=><article className="info-card" key={item._id}><Award/><h3>{item.title}</h3><p className="meta">{item.organization} {item.year?`· ${item.year}`:''}</p><p>{item.description}</p>{item.link&&<a href={item.link} target="_blank" rel="noreferrer">Open achievement <ArrowUpRight size={15}/></a>}</article>)}</div></Section>}
   {certificates.length>0&&<Section id="certificates" eyebrow="07 / CERTIFICATES" title="Proof of continuous learning." accent><div className="timeline-grid">{certificates.map(item=><article className="info-card" key={item._id}><Award/><h3>{item.title}</h3><p className="meta">{item.issuer}</p><p>{item.issueDate?new Date(item.issueDate).getFullYear():''}{item.credentialId?` · ${item.credentialId}`:''}</p>{item.credentialUrl&&<a href={item.credentialUrl} target="_blank" rel="noreferrer">View credential <ArrowUpRight size={15}/></a>}</article>)}</div></Section>}
   <Section id="contact" eyebrow="08 / CONNECT" title="Let's build something useful." accent><div className="contact-panel"><div><p className="mini-label">LET'S CONNECT</p><h3>Have an idea, project or collaboration in mind?</h3><p className="text">Find my work, follow my technology journey, or send a message. I am always building, learning and exploring new ideas.</p></div><div className="contact-actions">{email&&<button className="contact-email" onClick={copyEmail}><Mail size={17}/><span>{copied?'Email copied!':email}</span>{copied?<Check size={15}/>:null}</button>}<div className="socials">{socials.map(([name,url])=><a key={name} href={url} target="_blank" rel="noreferrer"><MessageCircle size={17}/>{name}</a>)}</div></div></div></Section>
  </main>
  <footer><div><strong>{settings.siteName||profile.name||'Mukamyi Izere Arcange'}.</strong><span>© {year} {settings.copyrightText||'All rights reserved.'}</span></div><div><span>Built with code & curiosity.</span><a href="#home">Back to top ↑</a></div></footer>
 </div>
}
