import { useEffect, useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowUpRight, MessageCircle, Sparkles, Code2, Database, Bot, Monitor, GraduationCap, Award, FileText } from 'lucide-react';
import './styles.css';

const fallbackSkills=['Python','C','C++','Java','JavaScript','HTML5','CSS3','React.js','Node.js','Express.js','Electron.js','MongoDB','MySQL','SQL','NoSQL'];
const fallbackProjects=[
 {title:'Munyarwanda AI',category:'AI / RAG',description:'A Kinyarwanda-focused AI project exploring retrieval-augmented generation and AI integration.',icon:Bot},
 {title:'Arcange AI Assistant',category:'AI / Desktop',description:'A personal AI assistant concept combining desktop software with AI APIs.',icon:Monitor},
 {title:'NextBit Updates',category:'Technology Media',description:'A technology and ICT news brand focused on digital developments.',icon:Sparkles},
 {title:'NextByte Academy',category:'Education',description:'A technology learning platform concept for practical programming education.',icon:GraduationCap}
];
const fallbackSocials=[['GitHub','https://github.com/arcange9'],['Instagram','https://instagram.com/arcangegram'],['Telegram','https://t.me/izerearcange'],['Facebook','https://facebook.com/arcange.froky']];
function Section({eyebrow,title,children,id}){return <section id={id} className="section"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</section>}
export default function App(){
 const [content,setContent]=useState(null);
 useEffect(()=>{const api=import.meta.env.VITE_API_URL;if(!api)return;fetch(`${api}/api/content/public`).then(r=>r.ok?r.json():Promise.reject()).then(setContent).catch(()=>{});},[]);
 const profile=content?.profile||{}; const skills=content?.skills?.map(x=>x.name).filter(Boolean)||fallbackSkills; const projects=content?.projects?.length?content.projects:fallbackProjects; const experience=content?.experience?.[0]; const education=content?.education||[]; const achievements=content?.achievements||[]; const certificates=content?.certificates||[]; const settings=content?.settings||{}; const socials=content?.socials?.length?content.socials.map(x=>[x.label||x.platform,x.url]):fallbackSocials; const year=settings.autoUpdateCopyrightYear===false?settings.copyrightStartYear||new Date().getFullYear():new Date().getFullYear(); const colors={primary:'#8b5cf6',secondary:'#ff4ecd',accent:'#42e8ff',background:'#070711',surface:'#111120',text:'#f7f7fb',muted:'#aaaabd',...(settings.colors||{})};
 const theme=useMemo(()=>({'--primary':colors.primary,'--secondary':colors.secondary,'--accent':colors.accent,'--bg':colors.background,'--surface':colors.surface,'--text':colors.text,'--muted':colors.muted}),[colors.primary,colors.secondary,colors.accent,colors.background,colors.surface,colors.text,colors.muted]);
 return <div className="site" style={theme}><nav className="nav"><a className="logo" href="#home">ARCANGE<span>.</span></a><div className="links"><a href="#about">About</a><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#education">Education</a><a href="#experience">Experience</a><a href="#contact">Contact</a></div></nav><main>
 <section id="home" className="hero"><div className="orb orb1"/><div className="orb orb2"/><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="eyebrow">SOFTWARE • AI • COMPUTER SYSTEMS</motion.p><div className="hero-identity">{profile.photoUrl&&<img src={profile.photoUrl} alt={profile.name||'Profile'}/>}<div><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.1}}>{profile.name||'Mukamyi Izere Arcange'}</motion.h1><p className="lead">{profile.title||'Software developer, AI builder and Computer Systems & Architecture student creating practical digital experiences.'}</p></div></div><div className="actions"><a className="button primary" href="#projects">Explore my work <ArrowUpRight size={17}/></a>{profile.resumeUrl&&<a className="button" href={profile.resumeUrl} target="_blank" rel="noreferrer">View CV</a>}<a className="button" href="#contact">Contact me</a></div><div className="hero-tags">{skills.slice(0,7).map(s=><span key={s}>{s}</span>)}</div></section>
 <Section id="about" eyebrow="01 / ABOUT" title="Building with curiosity, code & technology."><p className="text">{profile.longBio||'I am focused on programming, web development, AI, databases and computer systems. This portfolio brings together the projects, technical interests, learning journey and experiments I build as I grow as a developer.'}</p><div className="feature-row"><div><Code2/><strong>Software</strong><span>Web & desktop applications</span></div><div><Bot/><strong>AI</strong><span>AI integration & RAG</span></div><div><Database/><strong>Data</strong><span>SQL & NoSQL databases</span></div></div></Section>
 <Section id="skills" eyebrow="02 / TECHNOLOGIES" title="My technical toolbox"><div className="skill-grid">{skills.map((s,i)=><motion.div whileHover={{y:-6}} className="skill" key={s}><small>{String(i+1).padStart(2,'0')}</small><strong>{s}</strong></motion.div>)}</div></Section>
 <Section id="projects" eyebrow="03 / SELECTED WORK" title="Projects with purpose."><div className="project-grid">{projects.map((p,i)=>{const Icon=p.icon||Sparkles;return <motion.article whileHover={{y:-7}} className="card" key={p._id||p.title||p.name}>{p.imageUrl&&<img className="card-image" src={p.imageUrl} alt={p.title}/>}<span>0{i+1}</span><Icon className="card-icon"/><p>{p.category||p.data?.category||'PROJECT'}</p><h3>{p.title||p.name}</h3><div>{p.description||p.data?.description||''}</div>{(p.githubUrl||p.liveUrl||p.data?.url)&&<a href={p.githubUrl||p.liveUrl||p.data.url} target="_blank" rel="noreferrer">View project <ArrowUpRight size={15}/></a>}</motion.article>})}</div></Section>
 {education.length>0&&<Section id="education" eyebrow="04 / EDUCATION" title="Learning and growing."><div className="timeline-grid">{education.map(item=><article className="info-card" key={item._id}><GraduationCap/><h3>{item.program}</h3><p className="meta">{item.institution}{item.level?` · ${item.level}`:''}</p><p>{item.startYear||''}{item.endYear?` — ${item.endYear}`:''}</p><p>{item.description}</p></article>)}</div></Section>}
 <Section id="experience" eyebrow="05 / TRAINING & EXPERIENCE" title="Learning through real programs."><div className="timeline-grid">{(content?.experience?.length?content.experience:[experience||{organization:'Ejo Labs — Technology Training Program',role:'Technology Training',type:'Training',description:'Participated in a one-month technology training program, developing practical knowledge around AI integration, Retrieval-Augmented Generation (RAG), software development and collaborative project work.'}]).map(item=><article className="experience" key={item._id||item.organization}><div className="experience-badge"><GraduationCap/></div><div><h3>{item.organization}</h3><p className="meta">{item.role||item.type}</p><p>{item.description}</p></div></article>)}</div></Section>
 {achievements.length>0&&<Section id="achievements" eyebrow="06 / ACHIEVEMENTS" title="Milestones worth remembering."><div className="timeline-grid">{achievements.map(item=><article className="info-card" key={item._id}><Award/><h3>{item.title}</h3><p className="meta">{item.organization} {item.year?`· ${item.year}`:''}</p><p>{item.description}</p>{item.link&&<a href={item.link} target="_blank" rel="noreferrer">Open achievement <ArrowUpRight size={15}/></a>}</article>)}</div></Section>}
 {certificates.length>0&&<Section id="certificates" eyebrow="07 / CERTIFICATES" title="Proof of continuous learning."><div className="timeline-grid">{certificates.map(item=><article className="info-card" key={item._id}><Award/><h3>{item.title}</h3><p className="meta">{item.issuer}</p><p>{item.issueDate?new Date(item.issueDate).getFullYear():''}{item.credentialId?` · ${item.credentialId}`:''}</p>{item.credentialUrl&&<a href={item.credentialUrl} target="_blank" rel="noreferrer">View credential <ArrowUpRight size={15}/></a>}</article>)}</div></Section>}
 <Section id="contact" eyebrow="08 / CONNECT" title="Let's build something useful."><p className="text">{profile.email?`Email me at ${profile.email}. `:''}Find my work, follow my technology journey, or connect with me.</p><div className="socials">{socials.map(([name,url])=><a key={name} href={url} target="_blank" rel="noreferrer"><MessageCircle size={17}/>{name}</a>)}</div></Section>
 </main><footer>© {year} {settings.siteName||profile.name||'Mukamyi Izere Arcange'}. {settings.copyrightText||'All rights reserved.'} <span>Built with code & curiosity.</span></footer></div>
}
